name: Build Unsigned APK

on:
#  push:
#    tags:
#      - 'v*'  # 触发条件：当推送标签以 'v' 开头时
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-22.04  # 使用最新的 Ubuntu 运行环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
#        with:
#          submodules: true


      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # 设置 JDK 版本
          distribution: 'temurin'  # 指定 JDK 发行版（例如 'adopt', 'zulu', 'temurin', 'oracle' 等）

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            curl \
            make \
            tar \
            libssl-dev \
            maven \
            unzip \
            python3 \
            git

      - name: Download Android Command Line Tools
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          mkdir -p $ANDROID_HOME/cmdline-tools
          curl -L -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
          rm cmdline-tools.zip

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.16.3'

      - name: Build APK
        run: |
          echo "Building libs"
          cd ~
          git clone -b main --depth=1 https://github.com/catpuppyapp/PuppyGit.git PuppyGit
          cd PuppyGit
          # 进入 lib_build_scripts 目录并执行构建脚本
          pushd lib_build_scripts
          bash 1_installrequire_no_sudo_and_apt.sh
          bash 2_downloadsrc.sh
          bash 2.5_buildjarlibs_fdroid.sh ~/PuppyGit/app/libs
          bash 3_buildlibs_fdroid.sh ~/PuppyGit/app/src/main/jniLibs/
          popd
          echo "Build apk"
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: unsigned-apk
          path: ~/PuppyGit/app/build/outputs/apk/release/app-release-unsigned.apk
